title: Yifan Huang's Workspace
page-top-title: Yifan Huang's Workspace
top-section-bg-text: Hi there👋
home-subtitle: Yifan Huang&ensp;|&ensp;黄一凡
copyright-text: '&copy; Yifan Huang 2023-2026. All Rights Reserved.'